#!/usr/bin/env python
"""Build CodeSearchNet single-statement completion data for multiple languages.

The pipeline reads raw CodeSearchNet function records, filters out unsuitable
functions (tests, generated code, commented code, noisy I/O, ...), extracts a
single "fill-in" statement per candidate (assignment / return / call), balances
the target kinds, and writes canonical + ChatML JSONL plus a report/preview.
"""
from __future__ import annotations

import argparse
import gzip
import hashlib
import json
import random
import re
import zipfile
from collections import Counter, defaultdict
from concurrent.futures import ProcessPoolExecutor
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Iterable, Iterator

# --------------------------------------------------------------------------- #
# Language configuration
# --------------------------------------------------------------------------- #
LANG_ALIASES = {
    "python": "python", "py": "python",
    "java": "java",
    "c": "c",
    "cpp": "cpp", "c++": "cpp",
    "csharp": "csharp", "c#": "csharp", "cs": "csharp",
    "javascript": "javascript", "js": "javascript", "node": "javascript",
    "go": "go", "golang": "go",
    "php": "php",
    "ruby": "ruby", "rb": "ruby",
}
LANG_DISPLAY = {
    "python": "Python", "java": "Java", "c": "C", "cpp": "C++", "csharp": "C#",
    "javascript": "JavaScript", "go": "Go", "php": "PHP", "ruby": "Ruby",
}
LANG_EXTS = {
    "python": (".py",),
    "java": (".java",),
    "c": (".c", ".h"),
    "cpp": (".cc", ".cpp", ".cxx", ".hpp", ".hh", ".hxx", ".h"),
    "csharp": (".cs",),
    "javascript": (".js", ".jsx", ".mjs", ".cjs"),
    "go": (".go",),
    "php": (".php", ".phtml"),
    "ruby": (".rb",),
}
TARGET_RATIOS = {"assignment": 0.45, "return": 0.30, "call": 0.25}

# --------------------------------------------------------------------------- #
# Filtering / classification patterns
# --------------------------------------------------------------------------- #
GENERATED_RE = re.compile(r"Code generated|DO NOT EDIT|generated by|<auto-generated", re.IGNORECASE)
TEST_PATH_RE = re.compile(
    r"(^|/)(test|tests|testing|testdata|vendor|mock|mocks|fixture|fixtures|example|examples|generated)(/|$)",
    re.IGNORECASE,
)
TEST_SYMBOL_RE = re.compile(
    r"\b(Test|Tests|Benchmark|Example|assert|Assert|require|expected|actual|fixture|mock|"
    r"pytest|unittest|junit|xunit|nunit)\b",
    re.IGNORECASE,
)
NOISY_RE = re.compile(
    r"\b(?:print|printf|println|Console\.Write|console\.(?:log|error|warn|info|debug)|"
    r"fmt\.Print|log\.Print|panic|exit|System\.out\.print|"
    r"puts|echo|print_r|var_dump|var_export|error_log)\b",
    re.IGNORECASE,
)
LOW_INFO_RETURNS = {
    "return nil", "return null", "return none", "return err", "return error",
    "return false", "return true", "return 0", "return -1", "return 1",
    'return ""', "return;",
}
PY_BLOCK_PREFIXES = (
    "if ", "for ", "while ", "with ", "try:", "except ", "finally:", "else:", "elif ",
    "class ", "def ", "async def ", "import ", "from ", "raise ", "yield ", "pass",
    "break", "continue", "global ", "nonlocal ", "@",
)
CLIKE_BLOCK_PREFIXES = (
    "if ", "for ", "while ", "switch ", "case ", "default:", "else", "try", "catch ",
    "finally", "class ", "struct ", "enum ", "namespace ", "using ", "import ",
    "package ", "#", "break;", "continue;", "throw ", "goto ", "do ", "template ", "typedef ",
)
# JavaScript is brace-based like C, but statements may omit the trailing
# semicolon (ASI) and identifiers may contain '$'.
JS_BLOCK_PREFIXES = (
    "if ", "if(", "for ", "for(", "while ", "while(", "switch ", "switch(",
    "case ", "default:", "else", "try", "catch", "finally", "do ", "do{",
    "function ", "function(", "function*", "class ", "import ", "export ",
    "throw ", "with ", "with(", "yield ", "yield*",
)
# Go is brace-based and also omits the trailing semicolon (inserted by the lexer).
GO_BLOCK_PREFIXES = (
    "if ", "for ", "for{", "switch ", "switch{", "select ", "select{", "case ",
    "default:", "else", "func ", "func(", "type ", "var ", "const ", "package ",
    "import ", "go ", "defer ", "range ", "struct", "interface", "map[", "chan ",
    "break", "continue", "fallthrough", "goto ", "label:",
)
# PHP is brace-based with required semicolons; variables are '$x'.
PHP_BLOCK_PREFIXES = (
    "if ", "if(", "for ", "for(", "foreach ", "foreach(", "while ", "while(",
    "switch ", "switch(", "case ", "default:", "do ", "do{", "else", "elseif",
    "function ", "function(", "class ", "interface ", "trait ", "namespace ",
    "use ", "public ", "private ", "protected ", "static ", "abstract ", "final ",
    "throw ", "try", "catch", "finally", "global ", "<?php", "?>", "#",
)
# Ruby uses def...end blocks, no braces, no semicolons; '#' comments.
RUBY_BLOCK_PREFIXES = (
    "def ", "class ", "module ", "if ", "unless ", "while ", "until ", "for ",
    "case ", "when ", "begin", "rescue", "ensure", "else", "elsif ", "end",
    "do ", "yield", "require ", "require_relative ", "include ", "extend ",
    "attr_", "raise ", "next", "break", "redo", "retry",
)
ASSIGN_RE = re.compile(r"(?<![=!<>:])(?::=|=|\+=|-=|\*=|/=|%=|&=|\|=|\^=|<<=|>>=)(?![=>])")
ASSIGN_SPLIT_RE = re.compile(r":=|\+=|-=|\*=|/=|%=|&=|\|=|\^=|<<=|>>=|=")
CALL_RE_PY = re.compile(r"^(?:await\s+)?(?:[A-Za-z_]\w*|[A-Za-z_]\w*(?:\.[A-Za-z_]\w*)+)\s*\(.*\)$")
CALL_RE_CLIKE = re.compile(r"^[A-Za-z_]\w*(?:(?:\.|::|->)[A-Za-z_]\w*)*\s*\(.*\)\s*;$")
CALL_RE_JS = re.compile(r"^(?:await\s+)?[A-Za-z_$][\w$]*(?:\.[A-Za-z_$][\w$]*)*\s*\(.*\)$")
CALL_RE_PHP = re.compile(r"^\$?[A-Za-z_]\w*(?:(?:->|::)\$?[A-Za-z_]\w*)*\s*\(.*\)\s*;$")
CALL_RE_RUBY = re.compile(r"^[A-Za-z_]\w*[!?]?(?:\.[A-Za-z_]\w*[!?]?)*\s*\(.*\)$")


# --------------------------------------------------------------------------- #
# Data containers
# --------------------------------------------------------------------------- #
@dataclass(frozen=True)
class RecordSource:
    kind: str
    path: Path
    member: str | None = None

    def label(self) -> str:
        return str(self.path) if self.member is None else f"{self.path}!{self.member}"


@dataclass(frozen=True)
class CandidateSpan:
    start: int
    end: int
    target: str
    target_kind: str
    line_no: int


@dataclass
class BuildStats:
    files_seen: int = 0
    rows_seen: int = 0
    candidates_seen: int = 0
    rows_accepted: int = 0
    reject_reasons: Counter[str] = field(default_factory=Counter)

    def reject(self, reason: str) -> None:
        self.reject_reasons[reason] += 1

    def accept(self) -> None:
        self.rows_accepted += 1


def merge_stats(dst: BuildStats, src: BuildStats) -> None:
    """Fold one BuildStats into another (used when combining worker results)."""
    dst.rows_seen += src.rows_seen
    dst.candidates_seen += src.candidates_seen
    dst.reject_reasons.update(src.reject_reasons)


# --------------------------------------------------------------------------- #
# Small helpers
# --------------------------------------------------------------------------- #
def stable_hash(text: str, n: int = 16) -> str:
    return hashlib.sha1(text.encode("utf-8", errors="ignore")).hexdigest()[:n]


def normalize_code(code: str) -> str:
    """Normalise string/number literals and whitespace for dedup comparison."""
    code = re.sub(r'"(?:[^"\\]|\\.)*"', '"STR"', code)
    code = re.sub(r"'(?:[^'\\]|\\.)*'", "'STR'", code)
    code = re.sub(r"\b\d+(?:\.\d+)?\b", "NUM", code)
    return re.sub(r"\s+", "", code)


def count_nonempty_lines(code: str) -> int:
    return sum(1 for line in code.splitlines() if line.strip())


def parse_languages(value: str) -> list[str]:
    out: list[str] = []
    for raw in value.split(","):
        key = raw.strip().lower()
        if not key:
            continue
        if key not in LANG_ALIASES:
            raise ValueError(f"unsupported language {raw!r}")
        lang = LANG_ALIASES[key]
        if lang not in out:
            out.append(lang)
    return out


# --------------------------------------------------------------------------- #
# Source discovery and record iteration
# --------------------------------------------------------------------------- #
def _source_in_split(src: RecordSource, split: str) -> bool:
    """True if a source file belongs to the given CSN split (train/valid/test).

    Matches the split as a path component (e.g. .../final/jsonl/train/...) or in
    the file name (e.g. go_train_0.jsonl.gz)."""
    ref = src.member if src.member else str(src.path)
    p = Path(ref)
    name = p.name.lower()
    return (split in [part.lower() for part in p.parts]
            or f"_{split}" in name or name.startswith(f"{split}_") or name.startswith(f"{split}."))


def discover_sources(root: Path, lang: str, split: str | None = None) -> list[RecordSource]:
    sources: list[RecordSource] = []
    names = [lang]
    if lang == "cpp":
        names += ["c++", "cplusplus"]
    if lang == "csharp":
        names += ["c#", "cs"]
    if lang == "javascript":
        names += ["js", "node", "nodejs"]
    if lang == "go":
        names += ["golang"]
    if lang == "ruby":
        names += ["rb"]

    found_subdir = False
    for name in names:
        base = root / name
        if base.exists():
            found_subdir = True
            sources += [RecordSource("jsonl", p) for p in sorted(base.rglob("*.jsonl"))]
            sources += [RecordSource("jsonl_gz", p) for p in sorted(base.rglob("*.jsonl.gz"))]
        archive = root / f"{name}.zip"
        if archive.exists():
            found_subdir = True
            with zipfile.ZipFile(archive) as zf:
                for member in sorted(zf.namelist()):
                    if member.endswith(".jsonl") or member.endswith(".jsonl.gz"):
                        sources.append(RecordSource("zip", archive, member))

    # Fallback: raw_root itself directly contains the *.jsonl[.gz] files,
    # e.g. --raw_root data/java/final/jsonl/train holding java_train_*.jsonl.gz
    # with no per-language subdirectory.
    if not found_subdir:
        sources += [RecordSource("jsonl", p) for p in sorted(root.rglob("*.jsonl"))]
        sources += [RecordSource("jsonl_gz", p) for p in sorted(root.rglob("*.jsonl.gz"))]

    if split:
        sources = [s for s in sources if _source_in_split(s, split)]

    return sources


def iter_json_lines_from_source(src: RecordSource) -> Iterator[str]:
    if src.kind == "jsonl":
        with src.path.open("rt", encoding="utf-8", errors="ignore") as f:
            yield from f
    elif src.kind == "jsonl_gz":
        with gzip.open(src.path, "rt", encoding="utf-8", errors="ignore") as f:
            yield from f
    elif src.kind == "zip":
        assert src.member is not None
        with zipfile.ZipFile(src.path) as zf:
            with zf.open(src.member) as raw:
                if src.member.endswith(".gz"):
                    with gzip.open(raw, "rt", encoding="utf-8", errors="ignore") as f:
                        yield from f
                else:
                    for b in raw:
                        yield b.decode("utf-8", errors="ignore")


def iter_records(src: RecordSource) -> Iterator[dict[str, Any]]:
    for line in iter_json_lines_from_source(src):
        line = line.strip()
        if not line:
            continue
        try:
            obj = json.loads(line)
        except json.JSONDecodeError:
            continue
        if isinstance(obj, dict):
            yield obj


# --------------------------------------------------------------------------- #
# Row-level filtering
# --------------------------------------------------------------------------- #
def get_code(row: dict[str, Any]) -> str:
    for key in ("code", "original_string", "func_code_string", "function", "content"):
        val = row.get(key)
        if isinstance(val, str) and val.strip():
            return val
    return ""


def split_line_comment(text: str, lang: str) -> tuple[str, bool]:
    """Return (code_without_trailing_comment, had_comment).

    Scans char-by-char so comment markers inside string/char literals are not
    mistaken for comments. Handles `#` for Python and `//` / `/*` for C-like
    and JavaScript. The code part is right-stripped; anything from the comment
    marker onward is dropped.
    """
    in_string: str | None = None
    escaped = False
    quotes = {'"', "'", "`"} if lang in ("javascript", "go") else {'"', "'"}
    hash_comment = lang in ("python", "ruby", "php")
    slash_comment = lang in ("c", "cpp", "csharp", "java", "javascript", "go", "php")
    for i, ch in enumerate(text):
        if in_string:
            if escaped:
                escaped = False
            elif ch == "\\":
                escaped = True
            elif ch == in_string:
                in_string = None
            continue
        if ch in quotes:
            in_string = ch
            continue
        if hash_comment and ch == "#":
            return text[:i].rstrip(), True
        if slash_comment and ch == "/" and i + 1 < len(text) and text[i + 1] in "/*":
            return text[:i].rstrip(), True
    return text, False


def should_reject_row(row: dict[str, Any], lang: str) -> str | None:
    path = str(row.get("path") or row.get("filepath") or row.get("file_path") or "")
    code = get_code(row)
    func_name = str(row.get("func_name") or row.get("function_name") or "")

    if not code.strip():
        return "missing_code"
    suffix = Path(path).suffix.lower() if path else ""
    if suffix and suffix not in LANG_EXTS[lang]:
        return "wrong_extension"
    if TEST_PATH_RE.search(path.replace("\\", "/")):
        return "test_path"
    if GENERATED_RE.search(code):
        return "generated_code"
    return None


# --------------------------------------------------------------------------- #
# Line / body geometry
# --------------------------------------------------------------------------- #
def line_offsets(code: str) -> Iterator[tuple[int, int, int, str]]:
    """Yield (line_no, start, end, text) where [start, end) covers the line
    content (excluding the trailing newline)."""
    offset = 0
    for line_no, raw in enumerate(code.splitlines(keepends=True), start=1):
        start = offset
        offset += len(raw)
        text = raw[:-1] if raw.endswith("\n") else raw
        if text.endswith("\r"):
            text = text[:-1]
        yield line_no, start, start + len(text), text


def py_body_start(code: str) -> int:
    """Return the offset where the function body begins, just after the
    `def ...:` header. Handles signatures that wrap across multiple lines."""
    rows = list(line_offsets(code))
    for i, (_, _, _, line) in enumerate(rows):
        stripped = line.strip()
        if not (stripped.startswith("def ") or stripped.startswith("async def ")):
            continue
        # Consume header lines until the parentheses are balanced and the line
        # closes the header with ':'.
        depth = 0
        for j in range(i, len(rows)):
            text = rows[j][3]
            depth += text.count("(") - text.count(")")
            if depth <= 0 and text.rstrip().endswith(":"):
                return rows[j + 1][1] if j + 1 < len(rows) else len(code)
        return len(code)
    return 0


def outer_brace_body(code: str) -> tuple[int, int] | None:
    """Return [start, end) of the outermost `{ ... }` body, skipping braces that
    appear inside string/char literals."""
    open_pos = code.find("{")
    if open_pos < 0:
        return None
    depth = 0
    in_string: str | None = None
    escaped = False
    for i in range(open_pos, len(code)):
        ch = code[i]
        if in_string:
            if escaped:
                escaped = False
            elif ch == "\\":
                escaped = True
            elif ch == in_string:
                in_string = None
            continue
        if ch in {'"', "'", "`"}:
            in_string = ch
            continue
        if ch == "{":
            depth += 1
        elif ch == "}":
            depth -= 1
            if depth == 0:
                return open_pos + 1, i
    return None


# --------------------------------------------------------------------------- #
# Statement classification
# --------------------------------------------------------------------------- #
def _looks_like_assignment(expr: str) -> str | None:
    """Return the LHS identifier if `expr` is a real assignment, else None."""
    if not ASSIGN_RE.search(expr):
        return None
    if any(op in expr for op in ("==", "!=", "<=", ">=")):
        return None
    lhs = ASSIGN_SPLIT_RE.split(expr, maxsplit=1)[0].strip()
    if lhs and lhs != "_":
        return lhs
    return None


def classify_target(line: str, lang: str) -> str | None:
    stripped = line.strip()
    if not stripped:
        return None
    lowered = stripped.lower()

    if lang == "python":
        if stripped.endswith(":") or any(lowered.startswith(p) for p in PY_BLOCK_PREFIXES):
            return None
        if "{" in stripped or "}" in stripped or ";" in stripped:
            return None
        if stripped.startswith("return"):
            if not re.match(r"^return\s+\S", stripped):
                return None
            if lowered in LOW_INFO_RETURNS:
                return None
            return "return"
        if _looks_like_assignment(stripped):
            return "assignment"
        if CALL_RE_PY.match(stripped):
            return "call"
        return None

    if lang in ("javascript", "go"):
        # Brace-based, but the trailing semicolon is optional (JS ASI / Go lexer).
        blocks = JS_BLOCK_PREFIXES if lang == "javascript" else GO_BLOCK_PREFIXES
        if "{" in stripped or "}" in stripped:
            return None
        if any(lowered.startswith(p) for p in blocks):
            return None
        core = stripped[:-1].strip() if stripped.endswith(";") else stripped
        if not core:
            return None
        if core.startswith("return"):
            if not re.match(r"^return\s+\S", core):
                return None
            if core.lower() in LOW_INFO_RETURNS:
                return None
            return "return"
        if _looks_like_assignment(core):
            return "assignment"
        if CALL_RE_JS.match(core):
            return "call"
        return None

    if lang == "php":
        if any(lowered.startswith(p) for p in PHP_BLOCK_PREFIXES):
            return None
        if "{" in stripped or "}" in stripped or not stripped.endswith(";"):
            return None
        core = stripped[:-1].strip()
        if core.startswith("return"):
            if not re.match(r"^return\s+\S", core):
                return None
            if core.lower() in LOW_INFO_RETURNS:
                return None
            return "return"
        if _looks_like_assignment(core):
            return "assignment"
        if CALL_RE_PHP.match(stripped):
            return "call"
        return None

    if lang == "ruby":
        # def...end blocks, no braces, no semicolons.
        if any(lowered.startswith(p) for p in RUBY_BLOCK_PREFIXES):
            return None
        if stripped.endswith(("do", "|", "{", "}", "=begin", "=end")):
            return None
        core = stripped
        if core.startswith("return"):
            if not re.match(r"^return\s+\S", core):
                return None
            if core.lower() in LOW_INFO_RETURNS:
                return None
            return "return"
        if _looks_like_assignment(core):
            return "assignment"
        if CALL_RE_RUBY.match(core):
            return "call"
        return None

    # C-like languages
    if any(lowered.startswith(p) for p in CLIKE_BLOCK_PREFIXES):
        return None
    if "{" in stripped or "}" in stripped or not stripped.endswith(";"):
        return None
    core = stripped[:-1].strip()
    lowered_core = core.lower()
    if core.startswith("return"):
        if not re.match(r"^return\s+\S", core):
            return None
        if lowered_core in LOW_INFO_RETURNS or lowered in LOW_INFO_RETURNS:
            return None
        return "return"
    if _looks_like_assignment(core):
        return "assignment"
    if CALL_RE_CLIKE.match(stripped):
        return "call"
    return None


def extract_statement_candidates(function_code: str, lang: str) -> tuple[list[CandidateSpan], str | None]:
    if lang == "python":
        body_start, body_end = py_body_start(function_code), len(function_code)
    else:
        bounds = outer_brace_body(function_code)
        body_start, body_end = bounds if bounds is not None else (0, len(function_code))

    body = function_code[body_start:body_end]
    line_count = count_nonempty_lines(body)
    if line_count < 2:
        return [], "function_too_short"
    if line_count > 150:
        return [], "function_too_long"

    out: list[CandidateSpan] = []
    for line_no, start, end, text in line_offsets(function_code):
        if end <= body_start or start >= body_end:
            continue
        # Noise (print/log) or test symbols (assert/Test) on this line -> try
        # the next line instead.
        if NOISY_RE.search(text) or TEST_SYMBOL_RE.search(text):
            continue
        # Trailing comment -> drop the comment, keep the code as the target.
        # Shrink the span so the comment text stays in the suffix and the full
        # code still reconstructs.
        code_text, had_comment = split_line_comment(text, lang)
        if had_comment:
            end = start + len(code_text)
            text = code_text
        if not text.strip():
            continue
        kind = classify_target(text, lang)
        if not kind:
            continue
        tokens = len(re.findall(r"[A-Za-z_]\w*|\S", text.strip()))
        if tokens < 3 or tokens > 60:
            continue
        out.append(CandidateSpan(start, end, text, kind, line_no))
    return out, None


# --------------------------------------------------------------------------- #
# Sample construction
# --------------------------------------------------------------------------- #
def make_canonical_sample(
    lang: str,
    row: dict[str, Any],
    source_label: str,
    cand: CandidateSpan,
    function_code: str,
    split: str = "train",
) -> dict[str, Any]:
    prefix = function_code[: cand.start]
    suffix = function_code[cand.end:]
    target = cand.target
    uid_base = "\n".join([
        str(row.get("repo", "")),
        str(row.get("path", "")),
        str(row.get("func_name", "")),
        source_label,
        str(cand.line_no),
        target,
    ])
    uid = f"codesearchnet_{lang}_single_{stable_hash(uid_base)}"
    return {
        "uid": uid,
        "source_dataset": f"codesearchnet_{lang}",
        "split": split,
        "language": LANG_DISPLAY[lang],
        "task_type": f"{lang}_single_statement_completion",
        "prefix": prefix,
        "target": target,
        "suffix": suffix,
        "full_code": prefix + target + suffix,
        "target_kind": cand.target_kind,
        "metadata": {
            "repo": row.get("repo"),
            "source_path": row.get("path"),
            "function_name": row.get("func_name"),
            "sha": row.get("sha"),
            "url": row.get("url"),
            "raw_source": source_label,
            "target_line": cand.line_no,
            "target_span": [cand.start, cand.end],
            "function_line_count": count_nonempty_lines(function_code),
            "filters": ["no_comments", "single_line", cand.target_kind],
        },
        "judge_payload": {"kind": "none"},
    }


def render_chatml(sample: dict[str, Any]) -> dict[str, Any]:
    lang_name = str(sample["language"])
    user = (
        f"Fill the [MASK] in the {lang_name} function. Return only the missing "
        f"{lang_name} code, without Markdown fences or explanation.\n\n"
        "* Incomplete Code:\n"
        f"{sample['prefix']}[MASK]{sample['suffix']}"
    )
    out = dict(sample)
    out["messages"] = [
        {"role": "system", "content": f"You are a {lang_name} code completion assistant."},
        {"role": "user", "content": user},
        {"role": "assistant", "content": sample["target"]},
    ]
    out["only_last_turn_loss"] = True
    return out


def select_balanced(samples: list[dict[str, Any]], n: int, seed: int) -> list[dict[str, Any]]:
    rng = random.Random(seed)
    if n <= 0 or len(samples) <= n:
        out = list(samples)
        rng.shuffle(out)
        return out

    by_kind: dict[str, list[dict[str, Any]]] = defaultdict(list)
    for s in samples:
        by_kind[s.get("target_kind", "unknown")].append(s)

    selected: list[dict[str, Any]] = []
    used: set[str] = set()
    for kind, ratio in TARGET_RATIOS.items():
        quota = int(round(n * ratio))
        bucket = by_kind.get(kind, [])
        rng.shuffle(bucket)
        for s in bucket[:quota]:
            selected.append(s)
            used.add(s["uid"])

    if len(selected) < n:
        rest = [s for s in samples if s["uid"] not in used]
        rng.shuffle(rest)
        selected.extend(rest[: n - len(selected)])

    rng.shuffle(selected)
    return selected[:n]


# --------------------------------------------------------------------------- #
# Per-source worker (parallel-safe)
# --------------------------------------------------------------------------- #
def process_one_source(task: tuple[RecordSource, str, int]):
    """Process a single source file in isolation.

    Runs in a worker process. Dedup is NOT done here, because the `seen` set
    cannot be shared across processes; instead each accepted sample is returned
    together with its dedup key, and the parent deduplicates globally.

    Returns (list[(key, sample)], BuildStats, source_label).
    """
    src, lang, max_source_rows, split = task
    stats = BuildStats()
    stats.files_seen = 1
    keyed_samples: list[tuple[str, dict[str, Any]]] = []

    for row in iter_records(src):
        if max_source_rows > 0 and stats.rows_seen >= max_source_rows:
            break
        stats.rows_seen += 1
        reason = should_reject_row(row, lang)
        if reason:
            stats.reject(reason)
            continue
        function_code = get_code(row)
        cands, reason = extract_statement_candidates(function_code, lang)
        if reason:
            stats.reject(reason)
            continue
        for cand in cands:
            stats.candidates_seen += 1
            key = stable_hash(normalize_code(function_code) + "\n" + normalize_code(cand.target))
            keyed_samples.append((key, make_canonical_sample(lang, row, src.label(), cand, function_code, split)))

    return keyed_samples, stats, src.label()


# --------------------------------------------------------------------------- #
# Output
# --------------------------------------------------------------------------- #
def write_jsonl(path: Path, rows: Iterable[dict[str, Any]]) -> int:
    path.parent.mkdir(parents=True, exist_ok=True)
    n = 0
    with path.open("w", encoding="utf-8") as f:
        for row in rows:
            f.write(json.dumps(row, ensure_ascii=False) + "\n")
            n += 1
    return n


def build_language(lang: str, raw_root: Path, split: str, cap: int, max_source_rows: int,
                   seed: int, workers: int = 1):
    sources = discover_sources(raw_root, lang, split)
    stats = BuildStats()
    samples: list[dict[str, Any]] = []
    seen: set[str] = set()

    def absorb(keyed_samples, sub_stats):
        stats.files_seen += 1
        merge_stats(stats, sub_stats)
        for key, sample in keyed_samples:
            if key in seen:
                stats.reject("duplicate_normalized")
                continue
            seen.add(key)
            samples.append(sample)
            stats.accept()

    tasks = [(src, lang, max_source_rows, split) for src in sources]

    if workers <= 1 or len(sources) <= 1:
        for task in tasks:
            keyed_samples, sub_stats, label = process_one_source(task)
            absorb(keyed_samples, sub_stats)
            print(f"[{lang}] done {label} "
                  f"(files {stats.files_seen}/{len(sources)}, accepted={stats.rows_accepted})",
                  flush=True)
    else:
        with ProcessPoolExecutor(max_workers=workers) as ex:
            for keyed_samples, sub_stats, label in ex.map(process_one_source, tasks):
                absorb(keyed_samples, sub_stats)
                print(f"[{lang}] done {label} "
                      f"(files {stats.files_seen}/{len(sources)}, accepted={stats.rows_accepted})",
                      flush=True)

    return select_balanced(samples, cap, seed), stats, [s.label() for s in sources]


def write_report(path: Path, jobs: list[dict[str, Any]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = ["# CodeSearchNet Multi-Language Single-Statement Data Report", ""]
    for job in jobs:
        lang, split, rows, stats = job["lang"], job["split"], job["rows"], job["stats"]
        sources = job["sources"]
        lines += [f"## {LANG_DISPLAY[lang]} / {lang}_single / {split}", ""]
        lines += [
            f"- sources: {len(sources)}",
            f"- files_seen: {stats.files_seen}",
            f"- rows_seen: {stats.rows_seen}",
            f"- candidates_seen: {stats.candidates_seen}",
            f"- accepted_before_sampling: {stats.rows_accepted}",
            f"- final_samples: {len(rows)}",
            "",
        ]
        lines.append("### target_kind")
        for kind, count in Counter(r.get("target_kind", "unknown") for r in rows).most_common():
            lines.append(f"- {kind}: {count}")
        lines += ["", "### reject_reasons"]
        for reason, count in stats.reject_reasons.most_common(30):
            lines.append(f"- {reason}: {count}")
        lines.append("")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def write_preview(path: Path, jobs: list[dict[str, Any]], seed: int, limit: int) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    rng = random.Random(seed)
    fences = {
        "python": "python", "java": "java", "c": "c", "cpp": "cpp",
        "csharp": "csharp", "javascript": "javascript",
        "go": "go", "php": "php", "ruby": "ruby",
    }
    lines = ["# CodeSearchNet Multi-Language Sample Preview", ""]
    for job in jobs:
        lang, split, rows = job["lang"], job["split"], job["rows"]
        sample_rows = list(rows)
        rng.shuffle(sample_rows)
        sample_rows = sample_rows[:limit]
        lines += [f"## {LANG_DISPLAY[lang]} / {split}", ""]
        for i, sample in enumerate(sample_rows, 1):
            lines += [
                f"### {i}. {sample['uid']} ({sample.get('target_kind')})",
                "",
                f"source_dataset: `{sample.get('source_dataset')}`",
                "",
                f"```{fences[lang]}",
                sample["prefix"] + "[MASK]" + sample["suffix"],
                "```",
                "",
                "target:",
                f"```{fences[lang]}",
                sample["target"],
                "```",
                "",
            ]
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


# --------------------------------------------------------------------------- #
# CLI
# --------------------------------------------------------------------------- #
def parse_args():
    p = argparse.ArgumentParser(
        description="Build CodeSearchNet single-statement completion data for multiple languages."
    )
    p.add_argument("--raw_root", type=Path, default=Path("data/"))
    p.add_argument("--output_root", type=Path, default=Path("data"))
    p.add_argument("--languages", default="go,java,javascript,php,python,ruby")
    p.add_argument(
        "--splits",
        default="train,valid,test",
        help="CSN splits to process. Only `train` is subsampled to --per_language; "
             "valid/test are emitted in full (no subsampling).",
    )
    p.add_argument(
        "--per_language",
        type=int,
        default=0,
        help="Subsample the train split to N balanced rows. 0 (default) = no "
             "subsampling (use all). valid/test are always emitted in full.",
    )
    p.add_argument(
        "--max_source_rows",
        type=int,
        default=0,
        help="Optional cap per source file before filtering; 0 means all rows. "
             "Note: with --workers > 1 this is per-file, not global.",
    )
    p.add_argument("--seed", type=int, default=42)
    p.add_argument(
        "--workers",
        type=int,
        default=1,
        help="Parallel worker processes per language (one source file per task).",
    )
    p.add_argument("--preview_per_lang", type=int, default=20)
    p.add_argument(
        "--report_path",
        type=Path,
        default=Path("outputs/docs/codesearchnet_multilang_single_report.md"),
    )
    p.add_argument(
        "--preview_path",
        type=Path,
        default=Path("outputs/docs/codesearchnet_multilang_single_preview.md"),
    )
    return p.parse_args()


def main():
    args = parse_args()
    langs = parse_languages(args.languages)
    splits = [s.strip() for s in args.splits.split(",") if s.strip()]
    jobs: list[dict[str, Any]] = []

    for lang in langs:
        for split in splits:
            # Only train is subsampled; valid/test are emitted in full.
            cap = args.per_language if split == "train" else 0
            rows, stats, sources = build_language(
                lang, args.raw_root, split, cap, args.max_source_rows, args.seed, args.workers
            )
            if not sources:
                print(f"[warn] no {split} sources found for {lang} under {args.raw_root}")
                continue

            out_dir = args.output_root / f"{lang}_single" / "train_data"
            canonical_path = out_dir / f"{lang}_single_{split}_codesearchnet_{len(rows)}_canonical.jsonl"
            chatml_path = out_dir / f"{lang}_single_{split}_codesearchnet_{len(rows)}_chatml.jsonl"
            write_jsonl(canonical_path, rows)
            write_jsonl(chatml_path, (render_chatml(r) for r in rows))
            print(
                f"[{lang}/{split}] sources={len(sources)} rows_seen={stats.rows_seen} "
                f"accepted_before_sampling={stats.rows_accepted} final={len(rows)} "
                f"{'(subsampled)' if cap else '(all)'} chatml={chatml_path}"
            )
            jobs.append({"lang": lang, "split": split, "rows": rows, "stats": stats, "sources": sources})

    write_report(args.report_path, jobs)
    write_preview(args.preview_path, jobs, args.seed, args.preview_per_lang)
    print(f"report={args.report_path}")
    print(f"preview={args.preview_path}")


if __name__ == "__main__":
    main()