#!/usr/bin/env python
from __future__ import annotations

import argparse
import ast
import hashlib
import json
import os
import random
import re
import sys
from collections import Counter, defaultdict
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Iterable, Iterator

ROOT = Path(__file__).resolve().parents[2]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from scripts.benchmark.benchmark_official_common import render_chatml_messages

LANGUAGES = {
    "python": {"data_dir": "data/python", "stack_lang": "Python", "exts": {"py"}},
    "java": {"data_dir": "data/java", "stack_lang": "Java", "exts": {"java"}},
    "cpp": {"data_dir": "data/c++", "stack_lang": "C++", "exts": {"cpp", "cc", "cxx", "c", "hpp", "hh", "hxx", "h"}},
    "csharp": {"data_dir": "data/c-sharp", "stack_lang": "C#", "exts": {"cs"}},
}

TASK_TYPES = ("algorithmic_block", "control_flow_expression", "api_function_call")
DEFAULT_TASK_RATIOS = {
    "algorithmic_block": 0.45,
    "control_flow_expression": 0.45,
    "api_function_call": 0.10,
}

PERMISSIVE_LICENSE_HINTS = (
    "mit",
    "apache",
    "bsd",
    "isc",
    "unlicense",
    "cc0",
    "boost",
    "zlib",
)

GENERATED_MARKERS = (
    "do not edit",
    "auto-generated",
    "autogenerated",
    "generated by",
    "this file was generated",
    "<auto-generated",
    "@generated",
)

BAD_PATH_RE = re.compile(
    r"(^|/|\\)(test|tests|testing|testdata|fixtures?|mocks?|mock|snapshots?|examples?|samples?|demo|demos|vendor|third[_-]?party|node_modules|dist|build|target|generated)(/|\\|$)",
    re.I,
)

CONFIG_PATH_RE = re.compile(
    r"(^|/|\\)(setup\.py|conf\.py|conftest\.py|package-info\.java|assemblyinfo\.cs|\.?settings|config|configs)(/|\\|$)",
    re.I,
)

CONTROL_KEYWORDS = {"if", "for", "while", "switch", "catch", "foreach", "using", "lock", "return", "sizeof", "typeof"}

# SAFIM official test context length p95, measured by
# scripts/data_process/analyze_official_fim_benchmark_data.py.
# context means len(prefix + suffix). These caps keep derived train data close
# to the benchmark's file-level snippet scale without forcing one global length.
OFFICIAL_CONTEXT_P95_CHARS = {
    "python": {
        "algorithmic_block": 2511,
        "control_flow_expression": 2404,
        "api_function_call": 3682,
    },
    "java": {
        "algorithmic_block": 2900,
        "control_flow_expression": 2942,
        "api_function_call": 4540,
    },
    "cpp": {
        "algorithmic_block": 1877,
        "control_flow_expression": 1972,
        "api_function_call": 4444,
    },
    "csharp": {
        "algorithmic_block": 10922,
        "control_flow_expression": 10991,
        "api_function_call": 3170,
    },
}

LOW_VALUE_CALLS = {
    "print",
    "println",
    "printf",
    "log",
    "debug",
    "info",
    "warn",
    "error",
    "assert",
    "require",
    "len",
    "str",
    "repr",
    "int",
    "float",
    "bool",
    "super",
}


@dataclass(frozen=True)
class SpanCandidate:
    task_type: str
    start: int
    end: int
    target_kind: str
    score: tuple[int, int, int]


def read_jsonl(path: Path) -> Iterator[dict[str, Any]]:
    if not path.exists():
        return
    with path.open("r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if line:
                yield json.loads(line)


def write_jsonl(path: Path, rows: Iterable[dict[str, Any]]) -> int:
    path.parent.mkdir(parents=True, exist_ok=True)
    n = 0
    with path.open("w", encoding="utf-8") as f:
        for row in rows:
            f.write(json.dumps(row, ensure_ascii=False) + "\n")
            n += 1
    return n


def write_json(path: Path, payload: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


def stable_hash(text: str) -> str:
    return hashlib.sha1(text.encode("utf-8", errors="replace")).hexdigest()


def normalize_code(text: str) -> str:
    text = text.replace("\r\n", "\n").replace("\r", "\n")
    text = re.sub(r"[ \t]+", " ", text)
    text = re.sub(r"\n+", "\n", text)
    return text.strip()


def line_offsets(text: str) -> list[int]:
    offsets = [0]
    for idx, ch in enumerate(text):
        if ch == "\n":
            offsets.append(idx + 1)
    return offsets


def span_from_lines(text: str, start_line: int, end_line: int) -> tuple[int, int]:
    offsets = line_offsets(text)
    start_idx = max(0, min(start_line - 1, len(offsets) - 1))
    end_idx = max(start_idx, min(end_line, len(offsets)))
    start = offsets[start_idx]
    end = offsets[end_idx] if end_idx < len(offsets) else len(text)
    return start, end


def slice_span(text: str, start: int, end: int) -> tuple[str, str, str]:
    return text[:start], text[start:end], text[end:]


def line_col_to_offset(offsets: list[int], lineno: int, col: int) -> int:
    return offsets[lineno - 1] + col


def get_row_path(row: dict[str, Any]) -> str:
    for key in ("max_stars_repo_path", "max_issues_repo_path", "max_forks_repo_path", "path"):
        value = row.get(key)
        if value:
            return str(value)
    return ""


def get_row_repo(row: dict[str, Any]) -> str:
    for key in ("max_stars_repo_name", "max_issues_repo_name", "max_forks_repo_name", "repo_name"):
        value = row.get(key)
        if value:
            return str(value)
    return ""


def get_row_licenses(row: dict[str, Any]) -> list[str]:
    values: list[str] = []
    for key in ("max_stars_repo_licenses", "max_issues_repo_licenses", "max_forks_repo_licenses", "licenses", "license"):
        value = row.get(key)
        if not value:
            continue
        if isinstance(value, str):
            values.append(value)
        elif isinstance(value, list):
            values.extend(str(x) for x in value if x)
    return sorted(set(values))


def has_permissive_license(row: dict[str, Any]) -> bool:
    licenses = get_row_licenses(row)
    if not licenses:
        return False
    joined = " ".join(licenses).lower()
    return any(hint in joined for hint in PERMISSIVE_LICENSE_HINTS)


def extension_from_path(path: str, fallback: str = "") -> str:
    suffix = Path(path).suffix.lower().lstrip(".")
    return suffix or fallback.lower().lstrip(".")


def strip_bom(text: str) -> str:
    return text.lstrip("\ufeff")


def _consume_block_comment(text: str, pos: int) -> int | None:
    if not text.startswith("/*", pos):
        return None
    end = text.find("*/", pos + 2)
    if end < 0:
        return None
    end += 2
    while end < len(text) and text[end] in " \t":
        end += 1
    if end < len(text) and text[end] == "\n":
        end += 1
    return end


def _consume_triple_string(text: str, pos: int) -> int | None:
    quote = None
    for candidate in ('"""', "'''"):
        if text.startswith(candidate, pos):
            quote = candidate
            break
    if quote is None:
        return None
    end = text.find(quote, pos + 3)
    if end < 0:
        return None
    end += 3
    while end < len(text) and text[end] in " \t":
        end += 1
    if end < len(text) and text[end] == "\n":
        end += 1
    return end


def strip_leading_comments(content: str, language: str) -> tuple[str, bool]:
    """Remove only file-opening comment/banner material before real code."""
    original = content
    text = strip_bom(content).replace("\r\n", "\n").replace("\r", "\n")
    pos = 0
    changed = text != original

    while True:
        before = pos
        while pos < len(text) and text[pos] in " \t\n":
            pos += 1

        if language == "python":
            line_end = text.find("\n", pos)
            line_end = len(text) if line_end < 0 else line_end
            stripped = text[pos:line_end].strip()
            if stripped.startswith("#!") or re.match(r"#.*coding[:=]", stripped):
                pos = min(line_end + 1, len(text))
                changed = True
                continue
            if stripped.startswith("#"):
                while pos < len(text):
                    line_end = text.find("\n", pos)
                    line_end = len(text) if line_end < 0 else line_end
                    stripped = text[pos:line_end].strip()
                    if stripped.startswith("#") or not stripped:
                        pos = min(line_end + 1, len(text))
                    else:
                        break
                changed = True
                continue
            triple_end = _consume_triple_string(text, pos)
            if triple_end is not None:
                pos = triple_end
                changed = True
                continue
        else:
            block_end = _consume_block_comment(text, pos)
            if block_end is not None:
                pos = block_end
                changed = True
                continue
            line_start = pos
            while pos < len(text):
                line_end = text.find("\n", pos)
                line_end = len(text) if line_end < 0 else line_end
                stripped = text[pos:line_end].strip()
                if stripped.startswith("//") or stripped.startswith("///") or not stripped:
                    pos = min(line_end + 1, len(text))
                else:
                    break
            if pos != line_start:
                changed = True
                continue

        if pos == before:
            break
        break

    return text[pos:], changed or pos > 0


def is_comment_only_or_empty(target: str) -> bool:
    stripped = target.strip()
    if not stripped:
        return True
    non_comment = []
    for line in stripped.splitlines():
        s = line.strip()
        if not s:
            continue
        if s.startswith(("#", "//", "/*", "*", "*/")):
            continue
        non_comment.append(s)
    return not non_comment


def is_low_value_target(target: str) -> bool:
    stripped = target.strip()
    if is_comment_only_or_empty(stripped):
        return True
    if stripped in {"pass", "break", "continue", "return", "return;", "return null;", "return None", "return true;", "return false;"}:
        return True
    if re.fullmatch(r"[{};]+", stripped):
        return True
    return False


def passes_target_length(task_type: str, target: str) -> bool:
    stripped = target.strip("\n")
    chars = len(stripped.strip())
    lines = sum(1 for line in stripped.splitlines() if line.strip()) or 1
    if task_type == "algorithmic_block":
        return 5 <= chars <= 300 and 1 <= lines <= 5
    if task_type == "control_flow_expression":
        return 3 <= chars <= 120 and lines == 1
    if task_type == "api_function_call":
        return 5 <= chars <= 220 and lines <= 3
    return False


def make_candidate(task_type: str, start: int, end: int, kind: str, score: tuple[int, int, int], content: str) -> SpanCandidate | None:
    if start < 0 or end <= start or end > len(content):
        return None
    target = content[start:end]
    if not passes_target_length(task_type, target):
        return None
    if is_low_value_target(target):
        return None
    return SpanCandidate(task_type, start, end, kind, score)


def file_filter_reason(row: dict[str, Any], language: str, args: argparse.Namespace) -> str | None:
    content = strip_bom(str(row.get("content") or "")).replace("\r\n", "\n").replace("\r", "\n")
    if len(content) < args.min_file_chars:
        return "too_short_file"
    if len(content) > args.max_file_chars:
        return "too_long_file"
    if content.count("\n") + 1 < args.min_file_lines:
        return "too_few_lines"
    if row.get("avg_line_length") and float(row["avg_line_length"]) > args.max_avg_line_length:
        return "avg_line_too_long"
    if row.get("max_line_length") and float(row["max_line_length"]) > args.max_line_length:
        return "max_line_too_long"
    head = content[:5000].lower()
    if any(marker in head for marker in GENERATED_MARKERS):
        return "generated_marker"
    path = get_row_path(row)
    repo = get_row_repo(row)
    pathish = f"{repo}/{path}"
    if BAD_PATH_RE.search(pathish):
        return "bad_path"
    if CONFIG_PATH_RE.search(pathish):
        return "config_path"
    ext = extension_from_path(path, str(row.get("ext") or ""))
    allowed = LANGUAGES[language]["exts"]
    if ext and ext not in allowed:
        return "bad_extension"
    if language == "cpp" and ext in {"h", "hh", "hpp", "hxx"}:
        if content.count("{") < 3 or not re.search(r"\)\s*(?:const\s*)?(?:noexcept\s*)?(?:->\s*[\w:<>,\s*&]+\s*)?\{", content):
            return "cpp_header_without_bodies"
    if language == "java":
        if re.search(r"\binterface\s+\w+", content) and content.count("{") <= 2:
            return "java_interface_only"
        if content.count(";") > 0 and content.count("if (") + content.count("for (") + content.count("while (") == 0 and content.count("return ") <= 1:
            return "java_pojo_like"
    if language == "csharp":
        if content.count("=>") + content.count(" get;") + content.count(" set;") > 8 and content.count("if (") + content.count("foreach (") + content.count("while (") == 0:
            return "csharp_model_like"
    if language == "python":
        if path.endswith("setup.py") or content.count("def ") + content.count("class ") == 0 and content.count("if ") < 2:
            return "python_config_or_no_logic"
    if args.require_permissive_license and not has_permissive_license(row):
        return "non_permissive_or_unknown_license"
    return None


def py_node_offsets(content: str, node: ast.AST, offsets: list[int]) -> tuple[int, int] | None:
    if not all(hasattr(node, attr) for attr in ("lineno", "col_offset", "end_lineno", "end_col_offset")):
        return None
    return line_col_to_offset(offsets, node.lineno, node.col_offset), line_col_to_offset(offsets, node.end_lineno, node.end_col_offset)


def collect_python_candidates(content: str) -> list[SpanCandidate]:
    try:
        tree = ast.parse(content)
    except SyntaxError:
        return []
    offsets = line_offsets(content)
    candidates: list[SpanCandidate] = []

    for node in ast.walk(tree):
        if isinstance(node, (ast.If, ast.While)):
            span = py_node_offsets(content, node.test, offsets)
            if span:
                c = make_candidate("control_flow_expression", span[0], span[1], type(node).__name__ + ".test", (4, span[1] - span[0], -span[0]), content)
                if c:
                    candidates.append(c)
        elif isinstance(node, (ast.For, ast.AsyncFor)):
            span = py_node_offsets(content, node.iter, offsets)
            if span:
                c = make_candidate("control_flow_expression", span[0], span[1], type(node).__name__ + ".iter", (3, span[1] - span[0], -span[0]), content)
                if c:
                    candidates.append(c)
        elif isinstance(node, ast.comprehension):
            span = py_node_offsets(content, node.iter, offsets)
            if span:
                c = make_candidate("control_flow_expression", span[0], span[1], "comprehension.iter", (1, span[1] - span[0], -span[0]), content)
                if c:
                    candidates.append(c)
            for cond in node.ifs:
                span = py_node_offsets(content, cond, offsets)
                if span:
                    c = make_candidate("control_flow_expression", span[0], span[1], "comprehension.if", (1, span[1] - span[0], -span[0]), content)
                    if c:
                        candidates.append(c)
        elif isinstance(node, ast.Call):
            span = py_node_offsets(content, node, offsets)
            if not span:
                continue
            target = content[span[0] : span[1]]
            callee = target.split("(", 1)[0].split(".")[-1].strip()
            if callee in LOW_VALUE_CALLS:
                continue
            score = (4 if "." in target.split("(", 1)[0] else 2, len(target), -span[0])
            c = make_candidate("api_function_call", span[0], span[1], "Call", score, content)
            if c:
                candidates.append(c)

    for parent in ast.walk(tree):
        bodies: list[list[ast.stmt]] = []
        for attr in ("body", "orelse", "finalbody"):
            body = getattr(parent, attr, None)
            if isinstance(body, list):
                bodies.append([x for x in body if isinstance(x, ast.stmt)])
        handlers = getattr(parent, "handlers", None)
        if isinstance(handlers, list):
            for handler in handlers:
                body = getattr(handler, "body", None)
                if isinstance(body, list):
                    bodies.append([x for x in body if isinstance(x, ast.stmt)])
        for body in bodies:
            if not body:
                continue
            for width in range(1, min(5, len(body)) + 1):
                for idx in range(0, len(body) - width + 1):
                    group = body[idx : idx + width]
                    start_line = group[0].lineno
                    end_line = group[-1].end_lineno
                    start, end = span_from_lines(content, start_line, end_line)
                    target = content[start:end]
                    interesting = sum(isinstance(x, (ast.Assign, ast.AnnAssign, ast.AugAssign, ast.Return, ast.Expr, ast.Break, ast.Continue)) for x in group)
                    score = (interesting, width, -start)
                    c = make_candidate("algorithmic_block", start, end, "statement_group", score, content)
                    if c:
                        candidates.append(c)
                if width >= 3:
                    break
    return dedup_candidates(candidates)


def find_matching_paren(text: str, open_idx: int) -> int | None:
    depth = 0
    quote: str | None = None
    escape = False
    for idx in range(open_idx, len(text)):
        ch = text[idx]
        if quote:
            if escape:
                escape = False
            elif ch == "\\":
                escape = True
            elif ch == quote:
                quote = None
            continue
        if ch in {'"', "'"}:
            quote = ch
            continue
        if ch == "(":
            depth += 1
        elif ch == ")":
            depth -= 1
            if depth == 0:
                return idx
    return None


def expression_before_paren(text: str, open_idx: int) -> tuple[int, str] | None:
    idx = open_idx - 1
    while idx >= 0 and text[idx].isspace():
        idx -= 1
    end = idx + 1
    allowed = set("abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789_.$:<>~")
    while idx >= 0 and text[idx] in allowed:
        idx -= 1
    start = idx + 1
    expr = text[start:end].strip()
    if not expr:
        return None
    return start, expr


def iter_control_parens(content: str) -> Iterator[tuple[int, int, str]]:
    for match in re.finditer(r"\b(if|while|for|switch|catch)\s*\(", content):
        open_idx = content.find("(", match.start())
        close_idx = find_matching_paren(content, open_idx)
        if close_idx is None:
            continue
        yield open_idx + 1, close_idx, match.group(1)


def iter_call_spans(content: str) -> Iterator[tuple[int, int, str]]:
    for match in re.finditer(r"\(", content):
        open_idx = match.start()
        before = expression_before_paren(content, open_idx)
        if not before:
            continue
        start, callee = before
        base = callee.split(".")[-1].split("::")[-1].split("->")[-1].strip("~")
        if not base or base in CONTROL_KEYWORDS or base in LOW_VALUE_CALLS:
            continue
        # Skip declarations like function foo(int x) by requiring either a receiver/namespace or assignment/call context.
        prefix = content[max(0, start - 20) : start]
        if "." not in callee and "::" not in callee and "->" not in callee and "new " not in prefix and "=" not in prefix and "return" not in prefix:
            continue
        close_idx = find_matching_paren(content, open_idx)
        if close_idx is None:
            continue
        yield start, close_idx + 1, "call_expression"


def collect_clike_block_candidates(content: str) -> list[SpanCandidate]:
    lines = content.split("\n")
    candidates: list[SpanCandidate] = []

    interesting_lines: list[tuple[int, int]] = []
    for line_no, line in enumerate(lines, start=1):
        stripped = line.strip()
        if not stripped or stripped.startswith(("//", "/*", "*", "#")):
            continue
        if stripped in {"{", "}", "};", "};"}:
            continue
        if any(k in stripped for k in ("=", "+=", "-=", "*=", "/=", "return", ".Add(", ".add(", ".push", ".append", "throw ")):
            if stripped.endswith((";", "}", ")")) or "return" in stripped:
                start, end = span_from_lines(content, line_no, line_no)
                interesting_lines.append((line_no, end - start))

    # Single lines and short contiguous groups are useful for SAFIM block_completion.
    max_idx = len(interesting_lines)
    for idx in range(max_idx):
        for width in range(1, min(5, max_idx - idx) + 1):
            group = interesting_lines[idx : idx + width]
            line_nums = [x[0] for x in group]
            if line_nums[-1] - line_nums[0] + 1 != width:
                break
            start, end = span_from_lines(content, line_nums[0], line_nums[-1])
            target = content[start:end]
            c = make_candidate("algorithmic_block", start, end, "statement_group", (width, len(target), -start), content)
            if c:
                candidates.append(c)

    # Prefer compact bodies immediately inside control braces.
    for match in re.finditer(r"\b(if|else|for|while|switch|case|try|catch)\b[^\n{;]*\{", content):
        brace = content.find("{", match.start())
        depth = 0
        end_brace = None
        for pos in range(brace, min(len(content), brace + 2000)):
            if content[pos] == "{":
                depth += 1
            elif content[pos] == "}":
                depth -= 1
                if depth == 0:
                    end_brace = pos
                    break
        if end_brace is None:
            continue
        start = brace + 1
        end = end_brace
        target = content[start:end]
        nonblank = [line for line in target.splitlines() if line.strip()]
        if 1 <= len(nonblank) <= 5:
            # Keep inner indentation and trailing newline when available.
            c = make_candidate("algorithmic_block", start, end, match.group(1) + "_body", (5, len(nonblank), -start), content)
            if c:
                candidates.append(c)
    return candidates


def collect_clike_candidates(content: str) -> list[SpanCandidate]:
    candidates: list[SpanCandidate] = []
    for start, end, keyword in iter_control_parens(content):
        c = make_candidate("control_flow_expression", start, end, keyword + "_condition", (4, end - start, -start), content)
        if c:
            candidates.append(c)
    for start, end, kind in iter_call_spans(content):
        target = content[start:end]
        score = (4 if any(x in target.split("(", 1)[0] for x in (".", "::", "->")) else 2, len(target), -start)
        c = make_candidate("api_function_call", start, end, kind, score, content)
        if c:
            candidates.append(c)
    candidates.extend(collect_clike_block_candidates(content))
    return dedup_candidates(candidates)


def dedup_candidates(candidates: list[SpanCandidate]) -> list[SpanCandidate]:
    best: dict[tuple[str, int, int], SpanCandidate] = {}
    for candidate in candidates:
        key = (candidate.task_type, candidate.start, candidate.end)
        old = best.get(key)
        if old is None or candidate.score > old.score:
            best[key] = candidate
    return list(best.values())


def collect_candidates(content: str, language: str) -> list[SpanCandidate]:
    if language == "python":
        return collect_python_candidates(content)
    return collect_clike_candidates(content)


def select_candidate(candidates: list[SpanCandidate], task_type: str, used: set[tuple[int, int]], rng: random.Random) -> SpanCandidate | None:
    filtered = [c for c in candidates if c.task_type == task_type and (c.start, c.end) not in used]
    if not filtered:
        return None
    filtered.sort(key=lambda c: c.score, reverse=True)
    top = filtered[: min(20, len(filtered))]
    return rng.choice(top)


def target_counts(samples_per_language: int, ratios: dict[str, float]) -> dict[str, int]:
    raw = {task: samples_per_language * ratios[task] for task in TASK_TYPES}
    counts = {task: int(raw[task]) for task in TASK_TYPES}
    remainder = samples_per_language - sum(counts.values())
    order = sorted(TASK_TYPES, key=lambda t: raw[t] - counts[t], reverse=True)
    for task in order[:remainder]:
        counts[task] += 1
    return counts


def context_char_limit(language: str, task_type: str, args: argparse.Namespace) -> int | None:
    limits: list[int] = []
    if args.length_profile == "official_p95":
        limits.append(OFFICIAL_CONTEXT_P95_CHARS[language][task_type])
    if args.max_prompt_chars and args.max_prompt_chars > 0:
        limits.append(args.max_prompt_chars)
    if not limits:
        return None
    return min(limits)


def source_meta(row: dict[str, Any]) -> dict[str, Any]:
    keys = [
        "hexsha",
        "size",
        "ext",
        "lang",
        "avg_line_length",
        "max_line_length",
        "alphanum_fraction",
        "max_stars_repo_path",
        "max_stars_repo_name",
        "max_stars_repo_licenses",
        "max_issues_repo_path",
        "max_issues_repo_name",
        "max_issues_repo_licenses",
        "max_forks_repo_path",
        "max_forks_repo_name",
        "max_forks_repo_licenses",
    ]
    return {key: row.get(key) for key in keys if key in row}


def load_decontam_hashes(test_dir: Path) -> tuple[set[str], set[str]]:
    full_hashes: set[str] = set()
    target_hashes: set[str] = set()
    for path in test_dir.glob("safim_*.jsonl"):
        for row in read_jsonl(path):
            full_code = str(row.get("prefix", "")) + str(row.get("target", "")) + str(row.get("suffix", ""))
            target = str(row.get("target", ""))
            if full_code.strip():
                full_hashes.add(stable_hash(normalize_code(full_code)))
            if len(target.strip()) >= 40:
                target_hashes.add(stable_hash(normalize_code(target)))
    return full_hashes, target_hashes


def make_sample(row: dict[str, Any], content: str, language: str, candidate: SpanCandidate, source_index: int) -> dict[str, Any]:
    prefix, target, suffix = slice_span(content, candidate.start, candidate.end)
    if prefix + target + suffix != content:
        raise ValueError("internal span slicing error")
    path = get_row_path(row)
    repo = get_row_repo(row)
    uid_seed = f"{language}:{candidate.task_type}:{repo}:{path}:{candidate.start}:{candidate.end}:{stable_hash(content)}:{source_index}"
    uid = f"safim_train:{language}:{candidate.task_type}:{stable_hash(uid_seed)[:16]}"
    return {
        "uid": uid,
        "benchmark": "safim",
        "source": "derived_train",
        "source_dataset": "the_stack_v1",
        "language": language,
        "task_type": candidate.task_type,
        "official_task_id": uid,
        "entry_point": None,
        "prefix": prefix,
        "target": target,
        "suffix": suffix,
        "full_code": content,
        "target_kind": candidate.target_kind,
        "metadata": {
            "source_dataset": "the_stack_v1",
            "repo_name": repo,
            "path": path,
            "licenses": get_row_licenses(row),
            "target_start": candidate.start,
            "target_end": candidate.end,
            "target_chars": len(target),
            "target_lines": sum(1 for line in target.splitlines() if line.strip()),
            "raw_meta": source_meta(row),
        },
    }


def make_chatml_row(row: dict[str, Any]) -> dict[str, Any]:
    return {
        "uid": row["uid"],
        "benchmark": row["benchmark"],
        "source": row["source"],
        "source_dataset": row["source_dataset"],
        "language": row["language"],
        "task_type": row["task_type"],
        "official_task_id": row["official_task_id"],
        "prefix": row["prefix"],
        "target": row["target"],
        "suffix": row["suffix"],
        "messages": render_chatml_messages(row["language"], row["prefix"], row["suffix"]),
        "only_last_turn_loss": True,
        "metadata": row["metadata"],
    }


def load_stack_stream(language: str, token: str | bool | None) -> Iterable[dict[str, Any]]:
    try:
        from datasets import load_dataset
    except ImportError as exc:
        raise RuntimeError(
            "Missing dependency 'datasets'. Activate the eif-bench environment or install requirements.txt."
        ) from exc
    return load_dataset(
        "bigcode/the-stack",
        data_dir=LANGUAGES[language]["data_dir"],
        split="train",
        streaming=True,
        token=token,
    )


def build_language(language: str, args: argparse.Namespace, full_decontam: set[str], target_decontam: set[str]) -> tuple[list[dict[str, Any]], list[dict[str, Any]], dict[str, Any]]:
    rng = random.Random(args.seed + list(LANGUAGES).index(language) * 997)
    needed = target_counts(args.samples_per_language, args.task_ratios)
    counts = Counter()
    skipped = Counter()
    candidate_counts = Counter()
    selected: list[dict[str, Any]] = []
    source_pool: list[dict[str, Any]] = []
    used_file_hashes: set[str] = set()
    used_spans_by_file: dict[str, set[tuple[int, int]]] = defaultdict(set)
    token: str | bool | None = os.environ.get("HF_TOKEN") or True

    stream = load_stack_stream(language, token)
    scanned = 0
    kept_files = 0
    for source_index, row in enumerate(stream):
        if all(counts[task] >= needed[task] for task in TASK_TYPES):
            break
        scanned += 1
        if args.max_files_per_language and scanned > args.max_files_per_language:
            break
        raw_content = strip_bom(str(row.get("content") or "")).replace("\r\n", "\n").replace("\r", "\n")
        content = raw_content
        if args.strip_leading_comments:
            content, stripped_leading_comments = strip_leading_comments(raw_content, language)
            if stripped_leading_comments:
                skipped["stripped_leading_comments"] += 1
        row_for_filter = dict(row)
        row_for_filter["content"] = content
        row_for_filter["size"] = len(content)
        reason = file_filter_reason(row_for_filter, language, args)
        if reason:
            skipped[reason] += 1
            continue
        code_hash = stable_hash(normalize_code(content))
        if code_hash in used_file_hashes:
            skipped["duplicate_file"] += 1
            continue
        if code_hash in full_decontam:
            skipped["decontam_full_code"] += 1
            continue
        pathish = f"{get_row_repo(row)}/{get_row_path(row)}".lower()
        if any(key in pathish for key in ("safim", "human-eval", "humaneval", "benchmark")):
            skipped["benchmark_path"] += 1
            continue
        try:
            candidates = collect_candidates(content, language)
        except Exception as exc:
            skipped[f"candidate_exception:{type(exc).__name__}"] += 1
            continue
        if not candidates:
            skipped["no_candidates"] += 1
            continue
        for candidate in candidates:
            candidate_counts[candidate.task_type] += 1
        made = 0
        file_used = used_spans_by_file[code_hash]
        task_order = list(TASK_TYPES)
        rng.shuffle(task_order)
        for task_type in task_order:
            if counts[task_type] >= needed[task_type]:
                continue
            candidate = select_candidate(candidates, task_type, file_used, rng)
            if candidate is None:
                continue
            sample = make_sample(row, content, language, candidate, source_index)
            prompt_chars = len(sample["prefix"]) + len(sample["suffix"])
            prompt_limit = context_char_limit(language, task_type, args)
            if prompt_limit is not None and prompt_chars > prompt_limit:
                skipped[f"{task_type}:context_too_long"] += 1
                continue
            target_hash = stable_hash(normalize_code(sample["target"]))
            if len(sample["target"].strip()) >= 40 and target_hash in target_decontam:
                skipped[f"{task_type}:decontam_target"] += 1
                continue
            selected.append(sample)
            counts[task_type] += 1
            file_used.add((candidate.start, candidate.end))
            made += 1
        if made:
            kept_files += 1
            used_file_hashes.add(code_hash)
            source_pool.append(
                {
                    "source_dataset": "the_stack_v1",
                    "language": language,
                    "repo_name": get_row_repo(row),
                    "path": get_row_path(row),
                    "license": get_row_licenses(row),
                    "size": row.get("size") or len(content),
                    "content": content,
                    "raw_meta": source_meta(row),
                }
            )

    selected.sort(key=lambda x: (x["language"], x["task_type"], x["uid"]))
    report = {
        "language": language,
        "needed": dict(needed),
        "selected": dict(counts),
        "selected_total": len(selected),
        "scanned_files": scanned,
        "kept_source_files": kept_files,
        "skipped": dict(skipped),
        "candidate_counts": dict(candidate_counts),
    }
    missing = {task: needed[task] - counts[task] for task in TASK_TYPES if counts[task] < needed[task]}
    if missing:
        report["missing"] = missing
    return selected, source_pool, report


def parse_task_ratios(value: str) -> dict[str, float]:
    if not value:
        return dict(DEFAULT_TASK_RATIOS)
    ratios = dict(DEFAULT_TASK_RATIOS)
    for item in value.split(","):
        key, raw = item.split("=", 1)
        key = key.strip()
        if key not in TASK_TYPES:
            raise ValueError(f"unknown task type in --task-ratios: {key}")
        ratios[key] = float(raw)
    total = sum(ratios.values())
    if total <= 0:
        raise ValueError("task ratios must sum to a positive value")
    return {key: value / total for key, value in ratios.items()}


def prepare_viewer_data(out_dir: Path, viewer_dir: Path, test_dir: Path) -> dict[str, int]:
    viewer_dir.mkdir(parents=True, exist_ok=True)
    counts: dict[str, int] = {}
    for language in LANGUAGES:
        train_path = out_dir / f"safim_{language}_train_canonical.jsonl"
        train_rows = list(read_jsonl(train_path))
        counts[str(viewer_dir / f"train_safim_{language}.jsonl")] = write_jsonl(
            viewer_dir / f"train_safim_{language}.jsonl", train_rows
        )
        official_path = test_dir / f"safim_{language}.jsonl"
        if official_path.exists():
            official_rows = list(read_jsonl(official_path))
            counts[str(viewer_dir / f"official_safim_{language}.jsonl")] = write_jsonl(
                viewer_dir / f"official_safim_{language}.jsonl", official_rows
            )
    return counts


def main() -> None:
    parser = argparse.ArgumentParser(description="Build SAFIM-style multilingual FIM train data from The Stack v1 streaming source.")
    parser.add_argument("--out-dir", type=Path, default=Path("data/benchmark/train_data/safim"))
    parser.add_argument("--test-dir", type=Path, default=Path("data/benchmark/test_data"))
    parser.add_argument("--languages", nargs="+", choices=tuple(LANGUAGES), default=list(LANGUAGES))
    parser.add_argument("--samples-per-language", type=int, default=1000)
    parser.add_argument("--task-ratios", default="algorithmic_block=0.45,control_flow_expression=0.45,api_function_call=0.10")
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--max-files-per-language", type=int, default=200000)
    parser.add_argument("--min-file-chars", type=int, default=800)
    parser.add_argument("--max-file-chars", type=int, default=12000)
    parser.add_argument("--min-file-lines", type=int, default=20)
    parser.add_argument("--max-avg-line-length", type=float, default=160.0)
    parser.add_argument("--max-line-length", type=float, default=1000.0)
    parser.add_argument("--max-prompt-chars", type=int, default=0, help="Optional global context cap for len(prefix + suffix). 0 keeps only --length-profile caps.")
    parser.add_argument("--strip-leading-comments", action=argparse.BooleanOptionalAction, default=True, help="Strip only file-opening license/banner comments before filtering and slicing.")
    parser.add_argument("--length-profile", choices=("official_p95", "none"), default="official_p95")
    parser.add_argument("--allow-non-permissive-license", action="store_true")
    parser.add_argument("--prepare-viewer-data", action="store_true")
    parser.add_argument("--viewer-dir", type=Path, default=Path("outputs/benchmark/safim_stack_probe/viewer_data"))
    parser.add_argument("--no-strict-counts", action="store_true", help="Write partial output instead of failing if a bucket is underfilled.")
    args = parser.parse_args()
    args.task_ratios = parse_task_ratios(args.task_ratios)
    args.require_permissive_license = not args.allow_non_permissive_license

    full_decontam, target_decontam = load_decontam_hashes(args.test_dir)
    args.out_dir.mkdir(parents=True, exist_ok=True)

    all_rows: list[dict[str, Any]] = []
    reports: dict[str, Any] = {}
    written: dict[str, int] = {}
    for language in args.languages:
        rows, source_pool, report = build_language(language, args, full_decontam, target_decontam)
        reports[language] = report
        canonical_path = args.out_dir / f"safim_{language}_train_canonical.jsonl"
        chatml_path = args.out_dir / f"safim_{language}_train_chatml.jsonl"
        source_path = Path("data/raw_data/the_stack_v1/safim_source_pool") / f"{language}_sources.jsonl"
        written[str(canonical_path)] = write_jsonl(canonical_path, rows)
        written[str(chatml_path)] = write_jsonl(chatml_path, (make_chatml_row(row) for row in rows))
        written[str(source_path)] = write_jsonl(source_path, source_pool)
        all_rows.extend(rows)

    combined_canonical = args.out_dir / "safim_train_canonical.jsonl"
    combined_chatml = args.out_dir / "safim_train_chatml.jsonl"
    written[str(combined_canonical)] = write_jsonl(combined_canonical, all_rows)
    written[str(combined_chatml)] = write_jsonl(combined_chatml, (make_chatml_row(row) for row in all_rows))

    viewer_outputs = {}
    if args.prepare_viewer_data:
        viewer_outputs = prepare_viewer_data(args.out_dir, args.viewer_dir, args.test_dir)

    report = {
        "config": {
            "source": "bigcode/the-stack",
            "mode": "streaming",
            "languages": args.languages,
            "samples_per_language": args.samples_per_language,
            "task_ratios": args.task_ratios,
            "target_counts_per_language": target_counts(args.samples_per_language, args.task_ratios),
            "seed": args.seed,
            "max_files_per_language": args.max_files_per_language,
            "min_file_chars": args.min_file_chars,
            "max_file_chars": args.max_file_chars,
            "max_prompt_chars": args.max_prompt_chars,
            "strip_leading_comments": args.strip_leading_comments,
            "length_profile": args.length_profile,
            "official_context_p95_chars": OFFICIAL_CONTEXT_P95_CHARS if args.length_profile == "official_p95" else None,
            "require_permissive_license": args.require_permissive_license,
            "test_dir": str(args.test_dir),
        },
        "languages": reports,
        "written": written,
        "viewer_outputs": viewer_outputs,
        "total_rows": len(all_rows),
    }
    report_path = args.out_dir / "build_report.json"
    write_json(report_path, report)

    if not args.no_strict_counts:
        missing = {
            lang: data.get("missing")
            for lang, data in reports.items()
            if data.get("missing")
        }
        if missing:
            print(json.dumps(report, ensure_ascii=False, indent=2))
            raise SystemExit(f"underfilled SAFIM train buckets: {missing}")

    print(json.dumps({"report": str(report_path), "total_rows": len(all_rows), "written": written, "viewer_outputs": viewer_outputs}, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
