#!/usr/bin/env python
from __future__ import annotations

import argparse, gzip, hashlib, json, random, re, zipfile
from collections import Counter, defaultdict
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Iterable, Iterator

LANG_ALIASES = {"python":"python","py":"python","java":"java","c":"c","cpp":"cpp","c++":"cpp","csharp":"csharp","c#":"csharp","cs":"csharp"}
LANG_DISPLAY = {"python":"Python","java":"Java","c":"C","cpp":"C++","csharp":"C#"}
LANG_EXTS = {"python":(".py",),"java":(".java",),"c":(".c",".h"),"cpp":(".cc",".cpp",".cxx",".hpp",".hh",".hxx",".h"),"csharp":(".cs",)}
TARGET_RATIOS = {"assignment":0.45,"return":0.30,"call":0.25}
COMMENT_RE_CLIKE = re.compile(r"//|/\*|\*/")
COMMENT_RE_PY = re.compile("#|" + chr(39) * 3 + "|" + chr(34) * 3)
GENERATED_RE = re.compile(r"Code generated|DO NOT EDIT|generated by|<auto-generated", re.IGNORECASE)
TEST_PATH_RE = re.compile(r"(^|/)(test|tests|testing|testdata|vendor|mock|mocks|fixture|fixtures|example|examples|generated)(/|$)", re.IGNORECASE)
TEST_SYMBOL_RE = re.compile(r"\b(Test|Tests|Benchmark|Example|assert|Assert|require|expected|actual|fixture|mock|pytest|unittest|junit|xunit|nunit)\b", re.IGNORECASE)
NOISY_RE = re.compile(r"\b(?:print|printf|println|Console\.Write|fmt\.Print|log\.Print|panic|exit|System\.out\.print)\b", re.IGNORECASE)
LOW_INFO_RETURNS = {"return nil","return null","return none","return err","return error","return false","return true","return 0","return -1","return 1","return \"\"","return;"}
PY_BLOCK_PREFIXES = ("if ","for ","while ","with ","try:","except ","finally:","else:","elif ","class ","def ","async def ","import ","from ","raise ","yield ","pass","break","continue","global ","nonlocal ","@")
CLIKE_BLOCK_PREFIXES = ("if ","for ","while ","switch ","case ","default:","else","try","catch ","finally","class ","struct ","enum ","namespace ","using ","import ","package ","#","break;","continue;","throw ","goto ","do ","template ","typedef ")
ASSIGN_RE = re.compile(r"(?<![=!<>:])(?::=|=|\+=|-=|\*=|/=|%=|&=|\|=|\^=|<<=|>>=)(?![=>])")
CALL_RE_PY = re.compile(r"^(?:await\s+)?(?:[A-Za-z_]\w*|[A-Za-z_]\w*(?:\.[A-Za-z_]\w*)+)\s*\(.*\)$")
CALL_RE_CLIKE = re.compile(r"^(?:[A-Za-z_]\w*|[A-Za-z_]\w*(?:[.::->][A-Za-z_]\w*)+)\s*\(.*\)\s*;$")

@dataclass(frozen=True)
class RecordSource:
    kind: str
    path: Path
    member: str | None = None
    def label(self) -> str:
        return str(self.path) if self.member is None else f"{self.path}!{self.member}"

@dataclass(frozen=True)
class CandidateSpan:
    start: int; end: int; target: str; target_kind: str; line_no: int

@dataclass
class BuildStats:
    files_seen:int=0; rows_seen:int=0; candidates_seen:int=0; rows_accepted:int=0
    reject_reasons:Counter[str]=field(default_factory=Counter)
    target_kinds:Counter[str]=field(default_factory=Counter)
    def reject(self, reason:str)->None: self.reject_reasons[reason]+=1
    def accept(self, kind:str)->None: self.rows_accepted+=1; self.target_kinds[kind]+=1

def stable_hash(text:str,n:int=16)->str: return hashlib.sha1(text.encode('utf-8',errors='ignore')).hexdigest()[:n]
def normalize_code(code:str)->str:
    code=re.sub(r'"(?:[^"\\]|\\.)*"','"STR"',code); code=re.sub(r"'(?:[^'\\]|\\.)*'","'STR'",code)
    code=re.sub(r"\b\d+(?:\.\d+)?\b","NUM",code); return re.sub(r"\s+","",code)
def count_nonempty_lines(code:str)->int: return sum(1 for line in code.splitlines() if line.strip())
def parse_languages(value:str)->list[str]:
    out=[]
    for raw in value.split(','):
        key=raw.strip().lower()
        if not key: continue
        if key not in LANG_ALIASES: raise ValueError(f'unsupported language {raw!r}')
        lang=LANG_ALIASES[key]
        if lang not in out: out.append(lang)
    return out

def discover_sources(root:Path, lang:str)->list[RecordSource]:
    sources=[]; names=[lang]
    if lang=='cpp': names += ['c++','cplusplus']
    if lang=='csharp': names += ['c#','cs']
    for name in names:
        base=root/name
        if base.exists():
            sources += [RecordSource('jsonl',p) for p in sorted(base.rglob('*.jsonl'))]
            sources += [RecordSource('jsonl_gz',p) for p in sorted(base.rglob('*.jsonl.gz'))]
        z=root/f'{name}.zip'
        if z.exists():
            with zipfile.ZipFile(z) as zf:
                for member in sorted(zf.namelist()):
                    if member.endswith('.jsonl') or member.endswith('.jsonl.gz'): sources.append(RecordSource('zip',z,member))
    return sources

def iter_json_lines_from_source(src:RecordSource)->Iterator[str]:
    if src.kind=='jsonl':
        with src.path.open('rt',encoding='utf-8',errors='ignore') as f: yield from f
    elif src.kind=='jsonl_gz':
        with gzip.open(src.path,'rt',encoding='utf-8',errors='ignore') as f: yield from f
    elif src.kind=='zip':
        assert src.member is not None
        with zipfile.ZipFile(src.path) as zf:
            with zf.open(src.member) as raw:
                if src.member.endswith('.gz'):
                    with gzip.open(raw,'rt',encoding='utf-8',errors='ignore') as f: yield from f
                else:
                    for b in raw: yield b.decode('utf-8',errors='ignore')

def iter_records(src:RecordSource)->Iterator[dict[str,Any]]:
    for line in iter_json_lines_from_source(src):
        line=line.strip()
        if not line: continue
        try: obj=json.loads(line)
        except json.JSONDecodeError: continue
        if isinstance(obj,dict): yield obj

def get_code(row:dict[str,Any])->str:
    for key in ('code','original_string','func_code_string','function','content'):
        val=row.get(key)
        if isinstance(val,str) and val.strip(): return val
    return ''
def has_comment(code:str, lang:str)->bool: return bool((COMMENT_RE_PY if lang=='python' else COMMENT_RE_CLIKE).search(code))
def should_reject_row(row:dict[str,Any], lang:str)->str|None:
    path=str(row.get('path') or row.get('filepath') or row.get('file_path') or '')
    code=get_code(row); func_name=str(row.get('func_name') or row.get('function_name') or '')
    if not code.strip(): return 'missing_code'
    suffix=Path(path).suffix.lower() if path else ''
    if suffix and suffix not in LANG_EXTS[lang]: return 'wrong_extension'
    if TEST_PATH_RE.search(path.replace('\\','/')): return 'test_path'
    if GENERATED_RE.search(code): return 'generated_code'
    if TEST_SYMBOL_RE.search(func_name) or TEST_SYMBOL_RE.search(code): return 'test_symbol'
    if has_comment(code,lang): return 'code_has_comment'
    if NOISY_RE.search(code): return 'noisy_call'
    return None

def line_offsets(code:str):
    offset=0
    for line_no, raw in enumerate(code.splitlines(keepends=True),start=1):
        start=offset; end=offset+len(raw); offset=end
        text=raw[:-1] if raw.endswith('\n') else raw
        if text.endswith('\r'): text=text[:-1]
        yield line_no,start,start+len(text),text

def py_body_start(code:str)->int:
    rows=list(line_offsets(code))
    for i,(_,_,_,line) in enumerate(rows):
        s=line.strip()
        if s.startswith('def ') or s.startswith('async def '): return rows[i+1][1] if i+1<len(rows) else len(code)
    return 0

def outer_brace_body(code:str)->tuple[int,int]|None:
    open_pos=code.find('{')
    if open_pos<0: return None
    depth=0; in_string=None; escaped=False
    for i in range(open_pos,len(code)):
        ch=code[i]
        if in_string:
            if escaped: escaped=False
            elif ch=='\\': escaped=True
            elif ch==in_string: in_string=None
            continue
        if ch in {'"',"'",'`'}: in_string=ch; continue
        if ch=='{': depth+=1
        elif ch=='}':
            depth-=1
            if depth==0: return open_pos+1,i
    return None

def classify_target(line:str, lang:str)->str|None:
    stripped=line.strip()
    if not stripped: return None
    lowered=stripped.lower()
    if lang=='python':
        if stripped.endswith(':') or any(lowered.startswith(p) for p in PY_BLOCK_PREFIXES): return None
        if '{' in stripped or '}' in stripped or ';' in stripped: return None
        if stripped.startswith('return'):
            if not re.match(r'^return\s+\S',stripped): return None
            if lowered in LOW_INFO_RETURNS: return None
            return 'return'
        if ASSIGN_RE.search(stripped) and '==' not in stripped and '!=' not in stripped and '<=' not in stripped and '>=' not in stripped:
            lhs=re.split(r':=|\+=|-=|\*=|/=|%=|&=|\|=|\^=|<<=|>>=|=',stripped,maxsplit=1)[0].strip()
            if lhs and lhs!='_': return 'assignment'
        if CALL_RE_PY.match(stripped): return 'call'
        return None
    if any(lowered.startswith(p) for p in CLIKE_BLOCK_PREFIXES): return None
    if '{' in stripped or '}' in stripped or not stripped.endswith(';'): return None
    core=stripped[:-1].strip(); lowered_core=core.lower()
    if core.startswith('return'):
        if not re.match(r'^return\s+\S',core): return None
        if lowered_core in LOW_INFO_RETURNS or lowered in LOW_INFO_RETURNS: return None
        return 'return'
    if ASSIGN_RE.search(core) and '==' not in core and '!=' not in core and '<=' not in core and '>=' not in core:
        lhs=re.split(r':=|\+=|-=|\*=|/=|%=|&=|\|=|\^=|<<=|>>=|=',core,maxsplit=1)[0].strip()
        if lhs and lhs!='_': return 'assignment'
    if CALL_RE_CLIKE.match(stripped): return 'call'
    return None

def extract_statement_candidates(function_code:str, lang:str)->tuple[list[CandidateSpan],str|None]:
    if has_comment(function_code,lang): return [],'function_has_comment'
    if GENERATED_RE.search(function_code): return [],'generated_code'
    if TEST_SYMBOL_RE.search(function_code): return [],'test_symbol_in_function'
    if NOISY_RE.search(function_code): return [],'noisy_call_in_function'
    if lang=='python': body_start,body_end=py_body_start(function_code),len(function_code)
    else:
        bounds=outer_brace_body(function_code); body_start,body_end=bounds if bounds is not None else (0,len(function_code))
    body=function_code[body_start:body_end]; lc=count_nonempty_lines(body)
    if lc<2: return [],'function_too_short'
    if lc>100: return [],'function_too_long'
    out=[]
    for line_no,start,end,text in line_offsets(function_code):
        if end<=body_start or start>=body_end: continue
        kind=classify_target(text,lang)
        if not kind: continue
        tok=len(re.findall(r'[A-Za-z_]\w*|\S',text.strip()))
        if tok<3 or tok>60: continue
        out.append(CandidateSpan(start,end,text,kind,line_no))
    return out,None

def make_canonical_sample(lang:str,row:dict[str,Any],source_label:str,cand:CandidateSpan,function_code:str)->dict[str,Any]:
    prefix=function_code[:cand.start]; suffix=function_code[cand.end:]; target=cand.target
    uid_base='\n'.join([str(row.get('repo','')),str(row.get('path','')),str(row.get('func_name','')),source_label,str(cand.line_no),target])
    uid=f'codesearchnet_{lang}_single_{stable_hash(uid_base)}'
    return {'uid':uid,'source_dataset':f'codesearchnet_{lang}','split':'train','language':LANG_DISPLAY[lang],
        'task_type':f'{lang}_single_statement_completion','prefix':prefix,'target':target,'suffix':suffix,
        'full_code':prefix+target+suffix,'target_kind':cand.target_kind,
        'metadata':{'repo':row.get('repo'),'source_path':row.get('path'),'function_name':row.get('func_name'),
            'sha':row.get('sha'),'url':row.get('url'),'raw_source':source_label,'target_line':cand.line_no,
            'target_span':[cand.start,cand.end],'function_line_count':count_nonempty_lines(function_code),
            'filters':['no_comments','single_line',cand.target_kind]},'judge_payload':{'kind':'none'}}

def render_chatml(sample:dict[str,Any])->dict[str,Any]:
    lang_name=str(sample['language'])
    user=(f'Fill the [MASK] in the {lang_name} function. Return only the missing {lang_name} code, '
          'without Markdown fences or explanation.\n\n* Incomplete Code:\n'
          f"{sample['prefix']}[MASK]{sample['suffix']}")
    out=dict(sample)
    out['messages']=[{'role':'system','content':f'You are a {lang_name} code completion assistant.'},{'role':'user','content':user},{'role':'assistant','content':sample['target']}]
    out['only_last_turn_loss']=True
    return out

def select_balanced(samples:list[dict[str,Any]], n:int, seed:int)->list[dict[str,Any]]:
    rng=random.Random(seed)
    if n<=0 or len(samples)<=n:
        out=list(samples); rng.shuffle(out); return out
    by_kind=defaultdict(list)
    for s in samples: by_kind[s.get('target_kind','unknown')].append(s)
    selected=[]; used=set()
    for kind,ratio in TARGET_RATIOS.items():
        quota=int(round(n*ratio)); bucket=by_kind.get(kind,[]); rng.shuffle(bucket)
        for s in bucket[:quota]: selected.append(s); used.add(s['uid'])
    if len(selected)<n:
        rest=[s for s in samples if s['uid'] not in used]; rng.shuffle(rest); selected.extend(rest[:n-len(selected)])
    rng.shuffle(selected); return selected[:n]

def write_jsonl(path:Path, rows:Iterable[dict[str,Any]])->int:
    path.parent.mkdir(parents=True,exist_ok=True); n=0
    with path.open('w',encoding='utf-8') as f:
        for row in rows: f.write(json.dumps(row,ensure_ascii=False)+'\n'); n+=1
    return n

def build_language(lang:str, raw_root:Path, per_language:int, max_source_rows:int, seed:int):
    sources=discover_sources(raw_root,lang); stats=BuildStats(); samples=[]; seen=set()
    for src in sources:
        stats.files_seen+=1
        for row in iter_records(src):
            if max_source_rows>0 and stats.rows_seen>=max_source_rows: break
            stats.rows_seen+=1
            reason=should_reject_row(row,lang)
            if reason: stats.reject(reason); continue
            function_code=get_code(row); cands,reason=extract_statement_candidates(function_code,lang)
            if reason: stats.reject(reason); continue
            for cand in cands:
                stats.candidates_seen+=1; key=stable_hash(normalize_code(function_code)+'\n'+normalize_code(cand.target))
                if key in seen: stats.reject('duplicate_normalized'); continue
                seen.add(key); samples.append(make_canonical_sample(lang,row,src.label(),cand,function_code)); stats.accept(cand.target_kind)
        if max_source_rows>0 and stats.rows_seen>=max_source_rows: break
    return select_balanced(samples,per_language,seed),stats,[s.label() for s in sources]

def write_report(path:Path, rows_by_lang, stats_by_lang, sources_by_lang)->None:
    path.parent.mkdir(parents=True,exist_ok=True); lines=['# CodeSearchNet Multi-Language Single-Statement Data Report','']
    for lang,rows in rows_by_lang.items():
        stats=stats_by_lang[lang]; lines += [f'## {LANG_DISPLAY[lang]} / {lang}_single','']
        lines += [f'- sources: {len(sources_by_lang[lang])}',f'- files_seen: {stats.files_seen}',f'- rows_seen: {stats.rows_seen}',f'- candidates_seen: {stats.candidates_seen}',f'- accepted_before_sampling: {stats.rows_accepted}',f'- final_samples: {len(rows)}','']
        lines.append('### target_kind')
        for kind,count in Counter(r.get('target_kind','unknown') for r in rows).most_common(): lines.append(f'- {kind}: {count}')
        lines += ['','### reject_reasons']
        for reason,count in stats.reject_reasons.most_common(30): lines.append(f'- {reason}: {count}')
        lines.append('')
    path.write_text('\n'.join(lines)+'\n',encoding='utf-8')

def write_preview(path:Path, rows_by_lang, seed:int, limit:int)->None:
    path.parent.mkdir(parents=True,exist_ok=True); rng=random.Random(seed); lines=['# CodeSearchNet Multi-Language Sample Preview','']; fences={'python':'python','java':'java','c':'c','cpp':'cpp','csharp':'csharp'}
    for lang,rows in rows_by_lang.items():
        sample_rows=list(rows); rng.shuffle(sample_rows); sample_rows=sample_rows[:limit]; lines += [f'## {LANG_DISPLAY[lang]}','']
        for i,sample in enumerate(sample_rows,1):
            lines += [f"### {i}. {sample['uid']} ({sample.get('target_kind')})",'',f"source_dataset: `{sample.get('source_dataset')}`",'',f"```{fences[lang]}",sample['prefix']+'[MASK]'+sample['suffix'],'```','','target:',f"```{fences[lang]}",sample['target'],'```','']
    path.write_text('\n'.join(lines)+'\n',encoding='utf-8')

def parse_args():
    p=argparse.ArgumentParser(description='Build CodeSearchNet single-statement completion data for multiple languages.')
    p.add_argument('--raw_root',type=Path,default=Path('data/go_single/raw_data/codesearchnet'))
    p.add_argument('--output_root',type=Path,default=Path('data'))
    p.add_argument('--languages',default='python,java,c,cpp,csharp')
    p.add_argument('--per_language',type=int,default=20000)
    p.add_argument('--max_source_rows',type=int,default=0,help='Optional cap per language before filtering; 0 means all available rows.')
    p.add_argument('--seed',type=int,default=42)
    p.add_argument('--preview_per_lang',type=int,default=20)
    p.add_argument('--report_path',type=Path,default=Path('outputs/docs/codesearchnet_multilang_single_report.md'))
    p.add_argument('--preview_path',type=Path,default=Path('outputs/docs/codesearchnet_multilang_single_preview.md'))
    return p.parse_args()

def main():
    args=parse_args(); langs=parse_languages(args.languages); rows_by_lang={}; stats_by_lang={}; sources_by_lang={}
    for lang in langs:
        rows,stats,sources=build_language(lang,args.raw_root,args.per_language,args.max_source_rows,args.seed)
        if not sources: print(f'[warn] no CodeSearchNet sources found for {lang} under {args.raw_root}')
        rows_by_lang[lang]=rows; stats_by_lang[lang]=stats; sources_by_lang[lang]=sources
        out_dir=args.output_root/f'{lang}_single'/'train_data'
        canonical_path=out_dir/f'{lang}_single_train_codesearchnet_{len(rows)}_canonical.jsonl'
        chatml_path=out_dir/f'{lang}_single_train_codesearchnet_{len(rows)}_chatml.jsonl'
        write_jsonl(canonical_path,rows); write_jsonl(chatml_path,(render_chatml(r) for r in rows))
        print(f'[{lang}] sources={len(sources)} rows_seen={stats.rows_seen} accepted_before_sampling={stats.rows_accepted} final={len(rows)} canonical={canonical_path} chatml={chatml_path}')
    write_report(args.report_path,rows_by_lang,stats_by_lang,sources_by_lang)
    write_preview(args.preview_path,rows_by_lang,args.seed,args.preview_per_lang)
    print(f'report={args.report_path}'); print(f'preview={args.preview_path}')

if __name__=='__main__': main()
